"""piki init — 初始化项目。

创建项目结构（instances/ + layouts/ 符合 ADR-001）、
写入配置文件、安装 Git hook、复制插件模板。
"""

from __future__ import annotations

import shutil
from pathlib import Path

from piki.core.plugin import discover_plugins


def _install_git_hook(target: Path) -> None:
    """在项目 .git/hooks 目录安装 pre-commit hook。

    如果目标目录不是 git 仓库，则跳过。
    如果 hook 已存在，不覆盖。
    """
    git_dir = target / ".git"
    if not git_dir.exists():
        return

    hook_path = git_dir / "hooks" / "pre-commit"
    hook_script = """#!/bin/bash
# Auto-generated by piki init
set -e
echo ">>> piki check..."
piki check
echo ">>> All checks passed."
"""
    if not hook_path.exists():
        hook_path.write_text(hook_script, encoding="utf-8")
        hook_path.chmod(0o755)


def _copytree(src: Path, dst: Path) -> None:
    """复制目录内容到目标目录（合并已有目录，不覆盖已有文件）。"""
    dst.mkdir(parents=True, exist_ok=True)
    for item in src.iterdir():
        target = dst / item.name
        if item.is_dir():
            # 目录合并：递归复制内容
            _copytree(item, target)
        elif not target.exists():
            shutil.copy2(item, target)


def cmd_init(path: str | None, plugin: str) -> int:
    """执行 init 命令。

    Args:
        path: 目标目录路径，None 表示当前目录。
        plugin: 要启用的插件名称。

    Returns:
        退出码：0 成功，1 失败（项目已存在或插件不存在）。
    """
    target = Path(path or ".").resolve()
    target.mkdir(parents=True, exist_ok=True)

    piki_toml = target / "piki.toml"
    if piki_toml.exists():
        print(f"Project already initialized at {target}")
        return 1

    plugins = discover_plugins()
    if plugin not in plugins:
        print(f"Unknown plugin: {plugin}")
        print(f"Available plugins: {', '.join(sorted(plugins))}")
        return 1

    # 写入 piki.toml
    piki_toml.write_text(
        f'[project]\nname = "{target.name or "my-project"}"\nversion = "1.0.0"\n\n'
        f'[plugins]\nenabled = ["{plugin}"]\n\n'
        f"[plugins.{plugin}]\n"
        f"power_threshold = 0.4\nrack_usage_threshold = 0.8\n",
        encoding="utf-8",
    )

    # 写入 .gitignore
    gitignore = target / ".gitignore"
    if not gitignore.exists():
        gitignore.write_text(".piki_cache/\nreports/\n", encoding="utf-8")

    # 安装 Git pre-commit hook
    _install_git_hook(target)

    # 先复制模板（模板可能包含自己的 instances/ layouts/ 等目录）
    template_dir = Path(__file__).parent.parent / "templates" / plugin
    if template_dir.exists():
        _copytree(template_dir, target)

    # 确保 ADR-001 / ADR-011 标准目录存在（模板可能已有，不会覆盖）
    (target / "instances").mkdir(exist_ok=True)
    (target / "layouts").mkdir(exist_ok=True)
    (target / "catalogs" / "components").mkdir(parents=True, exist_ok=True)
    (target / "catalogs" / "service-methods").mkdir(parents=True, exist_ok=True)

    print(f"Initialized piki project at {target} with plugin '{plugin}'")
    return 0
